//
// Created by konstantin on 1/4/21.
//

#ifndef MRTPHASESIMULATION_LIBSPHASEDEFINITIONSANDCONSTANTS_H
#define MRTPHASESIMULATION_LIBSPHASEDEFINITIONSANDCONSTANTS_H

#include <string>
#define SPhaseFile_FORMAT_ID "SPhaseFile"
#define SPhaseFile_VERSION_ID "0.0.1"

#endif //MRTPHASESIMULATION_LIBSPHASEDEFINITIONSANDCONSTANTS_H
